export const INCREMENT = "COUNTER/INCREMENT";
export const DECREMENT = "COUNTER/DECREMENT";
export const ASYNC_INCREMENT = "COUNTER/ASYNC_INCREMENT";
export const CHANGE_THEME = "APP/CHANGE_THEME";
export const DISABLE_BUTTONS = "APP/DISABLE_BUTTONS";
export const ENABLE_BUTTONS = "APP/ENABLE_BUTTONS";
